# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Abkao' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks

use_frameworks!
  # Pods for Abkao

pod 'Alamofire'
pod 'ReachabilitySwift', '~> 3'


end
